#!/bin/sh

set -e

if [ "$(id -u)" -eq 0 ]; then
    echo >&2 "Error: $0 is intended to be run as a user with sudo access"
    exit 1
fi

alias pacman="sudo pacman --noconfirm"

sudo sed -i -e '/^OPTIONS=/s/libtool/!libtool/' /etc/makepkg.conf
CPUS=$(grep -c processor /proc/cpuinfo)
JOBS=$(expr $CPUS \* 3 / 2)
sudo sed -i -e "s,#*MAKEFLAGS=.*,MAKEFLAGS=\"-j$JOBS\"," /etc/makepkg.conf

curl https://github.com/kergoth/aur-dropbear/tarball/master | tar -zxvf -
cd kergoth-aur-dropbear-*
makepkg
pacman -U dropbear*xz
cd ..
sudo systemctl enable dropbear.socket

# Ensure we can build 32 bit binaries
yes | pacman -S binutils-multilib gcc-libs-multilib gcc-multilib

pacman -S nss-mdns avahi pkgfile git mercurial

sudo pkgfile -u


sudo sed -i -e '/hosts:/s/dns/mdns_minimal dns/' /etc/nsswitch.conf
sudo systemctl enable avahi-daemon.service
sudo systemctl start avahi-daemon.service || true

pacman -S vim tmux subversion python2 python2-pip

# Clean up
pacman -R ppp nano pcmciautils

# If vmware
if grep -q vmci /proc/misc; then
    pacman -S xf86-input-vmmouse xf86-video-vmware
    pacman -S open-vm-tools open-vm-tools-modules
    sudo systemctl enable vmtoolsd.service
    sudo systemctl start vmtoolsd.service || true
    sudo sed -i -e '/hgfs/d' /etc/fstab
    sudo sh -c "echo '.host:/   /mnt/hgfs   vmhgfs  defaults  0 0' >>/etc/fstab"
fi

# GUI bits
sudo ln -sf . /usr/bin/X11

pacman -S xorg-xrdb xorg-xauth xorg-server xorg-xinit slim xorg-xset autocutsel
pacman -S rxvt-unicode
sudo systemctl enable slim.service

cat >X20-local-fonts.conf <<END
Section "Files"
    FontPath     "/usr/share/fonts/local/"
EndSection
END
sudo mv X20-local-fonts.conf /etc/X11/xorg.conf.d/

# Install yaourt for builds from the AUR
pacman -S yajl
curl https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz | tar -zxvf -
cd package-query
makepkg -f
pacman -U package-query-*.tar.xz
cd ..

curl https://aur.archlinux.org/packages/ya/yaourt/yaourt.tar.gz | tar -zxvf -
cd yaourt
makepkg -f
pacman -U yaourt-*.tar.xz

yaourt -S urxvtcd
