#!/bin/sh

set -e

partition="${1:-/dev/sda1}"

mkfs.btrfs -f -L root /dev/sda1
mkdir /mnt2
mount /dev/sda1 /mnt2
cd /mnt2

btrfs subvolume create @
btrfs subvolume create @snapshots

mount -o subvol=@ "$partition" /mnt

mkdir -p @var/cache/pacman
for subvolume in @home @srv @var/log @var/tmp @var/cache/pacman/pkg @var/abs; do
    # btrfs subvolume create "$subvolume"
    # mkdir -p "/mnt/${subvolume#@}"
    mount -o subvol="$subvolume" "$partition" "/mnt/${subvolume#@}"
done
